//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 

#region Using directives

using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization;
using System.Xml;
using System.Xml.Schema;

#endregion

namespace SobekCM.METS_Editor.Tools
{
	[Serializable]
	[DesignerCategory("code")]
	[DebuggerStepThrough]
	[ToolboxItem(true)]
	public class Division_Types_Errors_Table : DataSet 
	{
   
		private Volume_Error_TypeDataTable tableVolume_Error_Type;
    
		private Division_TypeDataTable tableDivision_Type;
    
		private File_Error_TypeDataTable tableFile_Error_Type;
       
		public Division_Types_Errors_Table() 
		{
			InitClass();
			CollectionChangeEventHandler schemaChangedHandler = SchemaChanged;
			Tables.CollectionChanged += schemaChangedHandler;
			Relations.CollectionChanged += schemaChangedHandler;
		}
    
		protected Division_Types_Errors_Table(SerializationInfo info, StreamingContext context) 
		{
			string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
			if ((strSchema != null)) 
			{
				DataSet ds = new DataSet();
				ds.ReadXmlSchema(new XmlTextReader(new StringReader(strSchema)));
				if ((ds.Tables["Volume_Error_Type"] != null)) 
				{
					Tables.Add(new Volume_Error_TypeDataTable(ds.Tables["Volume_Error_Type"]));
				}
				if ((ds.Tables["Division_Type"] != null)) 
				{
					Tables.Add(new Division_TypeDataTable(ds.Tables["Division_Type"]));
				}
				if ((ds.Tables["File_Error_Type"] != null)) 
				{
					Tables.Add(new File_Error_TypeDataTable(ds.Tables["File_Error_Type"]));
				}
				DataSetName = ds.DataSetName;
				Prefix = ds.Prefix;
				Namespace = ds.Namespace;
				Locale = ds.Locale;
				CaseSensitive = ds.CaseSensitive;
				EnforceConstraints = ds.EnforceConstraints;
				Merge(ds, false, MissingSchemaAction.Add);
				InitVars();
			}
			else 
			{
				InitClass();
			}
			GetSerializationData(info, context);
			CollectionChangeEventHandler schemaChangedHandler = SchemaChanged;
			Tables.CollectionChanged += schemaChangedHandler;
			Relations.CollectionChanged += schemaChangedHandler;
		}
    
   
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		public Volume_Error_TypeDataTable Volume_Error_Type 
		{
			get 
			{
				return tableVolume_Error_Type;
			}
		}
    
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		public Division_TypeDataTable Division_Type 
		{
			get 
			{
				return tableDivision_Type;
			}
		}
    
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		public File_Error_TypeDataTable File_Error_Type 
		{
			get 
			{
				return tableFile_Error_Type;
			}
		}
    
		public override DataSet Clone() 
		{
			Division_Types_Errors_Table cln = ((Division_Types_Errors_Table)(base.Clone()));
			cln.InitVars();
			return cln;
		}
    
		protected override bool ShouldSerializeTables() 
		{
			return false;
		}
    
		protected override bool ShouldSerializeRelations() 
		{
			return false;
		}
    
		protected override void ReadXmlSerializable(XmlReader reader) 
		{
			Reset();
			DataSet ds = new DataSet();
			ds.ReadXml(reader);
			if ((ds.Tables["Volume_Error_Type"] != null)) 
			{
				Tables.Add(new Volume_Error_TypeDataTable(ds.Tables["Volume_Error_Type"]));
			}
			if ((ds.Tables["Division_Type"] != null)) 
			{
				Tables.Add(new Division_TypeDataTable(ds.Tables["Division_Type"]));
			}
			if ((ds.Tables["File_Error_Type"] != null)) 
			{
				Tables.Add(new File_Error_TypeDataTable(ds.Tables["File_Error_Type"]));
			}
			DataSetName = ds.DataSetName;
			Prefix = ds.Prefix;
			Namespace = ds.Namespace;
			Locale = ds.Locale;
			CaseSensitive = ds.CaseSensitive;
			EnforceConstraints = ds.EnforceConstraints;
			Merge(ds, false, MissingSchemaAction.Add);
			InitVars();
		}
    
		protected override XmlSchema GetSchemaSerializable() 
		{
			MemoryStream stream = new MemoryStream();
			WriteXmlSchema(new XmlTextWriter(stream, null));
			stream.Position = 0;
			return XmlSchema.Read(new XmlTextReader(stream), null);
		}
    
		internal void InitVars() 
		{
			tableVolume_Error_Type = ((Volume_Error_TypeDataTable)(Tables["Volume_Error_Type"]));
			if ((tableVolume_Error_Type != null)) 
			{
				tableVolume_Error_Type.InitVars();
			}
			tableDivision_Type = ((Division_TypeDataTable)(Tables["Division_Type"]));
			if ((tableDivision_Type != null)) 
			{
				tableDivision_Type.InitVars();
			}
			tableFile_Error_Type = ((File_Error_TypeDataTable)(Tables["File_Error_Type"]));
			if ((tableFile_Error_Type != null)) 
			{
				tableFile_Error_Type.InitVars();
			}
		}
    
		private void InitClass() 
		{
			DataSetName = "App_Wide_Tables";
			Prefix = "";
			Namespace = "";
			Locale = new CultureInfo("en-US");
			CaseSensitive = false;
			EnforceConstraints = true;
			tableVolume_Error_Type = new Volume_Error_TypeDataTable();
			Tables.Add(tableVolume_Error_Type);
			tableDivision_Type = new Division_TypeDataTable();
			Tables.Add(tableDivision_Type);
			tableFile_Error_Type = new File_Error_TypeDataTable();
			Tables.Add(tableFile_Error_Type);
		}
    
		private bool ShouldSerializeVolume_Status() 
		{
			return false;
		}
    
		private bool ShouldSerializeVolume_Error_Type() 
		{
			return false;
		}
    
		private bool ShouldSerializeDivision_Type() 
		{
			return false;
		}
    
		private bool ShouldSerializeFile_Error_Type() 
		{
			return false;
		}
    
		private bool ShouldSerializeFile_Type() 
		{
			return false;
		}
    
		private void SchemaChanged(object sender, CollectionChangeEventArgs e) 
		{
			if ((e.Action == CollectionChangeAction.Remove)) 
			{
				InitVars();
			}
		}

		public delegate void Volume_Error_TypeRowChangeEventHandler(object sender, Volume_Error_TypeRowChangeEvent e);
    
		public delegate void Division_TypeRowChangeEventHandler(object sender, Division_TypeRowChangeEvent e);
    
		public delegate void File_Error_TypeRowChangeEventHandler(object sender, File_Error_TypeRowChangeEvent e);
    
  
		[DebuggerStepThrough]
			public class Volume_Error_TypeDataTable : DataTable, IEnumerable 
		{
        
			private DataColumn columnVolumeErrorTypeID;
        
			private DataColumn columnShortDesc;
        
			private DataColumn columnLongDesc;
        
			private DataColumn columnUserSelectable;

			private DataColumn columnEnglish;
			
			private DataColumn columnFrench;

			private DataColumn columnSpanish;
        
			internal Volume_Error_TypeDataTable() : 
				base("Volume_Error_Type") 
			{
				InitClass();
			}
        
			internal Volume_Error_TypeDataTable(DataTable table) : 
				base(table.TableName) 
			{
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) 
				{
					CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) 
				{
					Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) 
				{
					Namespace = table.Namespace;
				}
				Prefix = table.Prefix;
				MinimumCapacity = table.MinimumCapacity;
				DisplayExpression = table.DisplayExpression;
			}
        
			[Browsable(false)]
			public int Count 
			{
				get 
				{
					return Rows.Count;
				}
			}
        
			internal DataColumn VolumeErrorTypeIDColumn 
			{
				get 
				{
					return columnVolumeErrorTypeID;
				}
			}
        
			internal DataColumn ShortDescColumn 
			{
				get 
				{
					return columnShortDesc;
				}
			}
        
			internal DataColumn LongDescColumn 
			{
				get 
				{
					return columnLongDesc;
				}
			}
        
			internal DataColumn UserSelectableColumn 
			{
				get 
				{
					return columnUserSelectable;
				}
			}

			internal DataColumn EnglishColumn 
			{
				get 
				{
					return columnEnglish;
				}
			}

			internal DataColumn SpanishColumn 
			{
				get 
				{
					return columnSpanish;
				}
			}

			internal DataColumn FrenchColumn 
			{
				get 
				{
					return columnFrench;
				}
			}
        
			public Volume_Error_TypeRow this[int index] 
			{
				get 
				{
					return ((Volume_Error_TypeRow)(Rows[index]));
				}
			}
        
			public event Volume_Error_TypeRowChangeEventHandler Volume_Error_TypeRowChanged;
        
			public event Volume_Error_TypeRowChangeEventHandler Volume_Error_TypeRowChanging;
        
			public event Volume_Error_TypeRowChangeEventHandler Volume_Error_TypeRowDeleted;
        
			public event Volume_Error_TypeRowChangeEventHandler Volume_Error_TypeRowDeleting;
        
			public void AddVolume_Error_TypeRow(Volume_Error_TypeRow row) 
			{
				Rows.Add(row);
			}
        
			public Volume_Error_TypeRow AddVolume_Error_TypeRow(int VolumeErrorTypeID, string ShortDesc, string LongDesc, bool UserSelectable) 
			{
				Volume_Error_TypeRow rowVolume_Error_TypeRow = ((Volume_Error_TypeRow)(NewRow()));
				rowVolume_Error_TypeRow.ItemArray = new object[] {
																	 VolumeErrorTypeID,
																	 ShortDesc,
																	 LongDesc,
																	 UserSelectable};
				Rows.Add(rowVolume_Error_TypeRow);
				return rowVolume_Error_TypeRow;
			}
        
			public IEnumerator GetEnumerator() 
			{
				return Rows.GetEnumerator();
			}
        
			public override DataTable Clone() 
			{
				Volume_Error_TypeDataTable cln = ((Volume_Error_TypeDataTable)(base.Clone()));
				cln.InitVars();
				return cln;
			}
        
			protected override DataTable CreateInstance() 
			{
				return new Volume_Error_TypeDataTable();
			}
        
			internal void InitVars() 
			{
				columnVolumeErrorTypeID = Columns["VolumeErrorTypeID"];
				columnShortDesc = Columns["ShortDesc"];
				columnLongDesc = Columns["LongDesc"];
				columnUserSelectable = Columns["UserSelectable"];
				columnEnglish = Columns["English"];
				columnFrench = Columns["French"];
				columnSpanish = Columns["Spanish"];
			}
        
			private void InitClass() 
			{
				columnVolumeErrorTypeID = new DataColumn("VolumeErrorTypeID", typeof(int), null, MappingType.Element);
				Columns.Add(columnVolumeErrorTypeID);
				columnShortDesc = new DataColumn("ShortDesc", typeof(string), null, MappingType.Element);
				Columns.Add(columnShortDesc);
				columnLongDesc = new DataColumn("LongDesc", typeof(string), null, MappingType.Element);
				Columns.Add(columnLongDesc);
				columnUserSelectable = new DataColumn("UserSelectable", typeof(bool), null, MappingType.Element);
				Columns.Add(columnUserSelectable);
				columnEnglish = new DataColumn("English", typeof(string), null, MappingType.Element);
				Columns.Add(columnEnglish);
				columnFrench = new DataColumn("French", typeof(string), null, MappingType.Element);
				Columns.Add(columnFrench);
				columnSpanish = new DataColumn("Spanish", typeof(string), null, MappingType.Element);
				Columns.Add(columnSpanish);
			}
        
			public Volume_Error_TypeRow NewVolume_Error_TypeRow() 
			{
				return ((Volume_Error_TypeRow)(NewRow()));
			}
        
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) 
			{
				return new Volume_Error_TypeRow(builder);
			}
        
			protected override Type GetRowType() 
			{
				return typeof(Volume_Error_TypeRow);
			}
        
			protected override void OnRowChanged(DataRowChangeEventArgs e) 
			{
				base.OnRowChanged(e);
				if ((Volume_Error_TypeRowChanged != null)) 
				{
					Volume_Error_TypeRowChanged(this, new Volume_Error_TypeRowChangeEvent(((Volume_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowChanging(DataRowChangeEventArgs e) 
			{
				base.OnRowChanging(e);
				if ((Volume_Error_TypeRowChanging != null)) 
				{
					Volume_Error_TypeRowChanging(this, new Volume_Error_TypeRowChangeEvent(((Volume_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowDeleted(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleted(e);
				if ((Volume_Error_TypeRowDeleted != null)) 
				{
					Volume_Error_TypeRowDeleted(this, new Volume_Error_TypeRowChangeEvent(((Volume_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowDeleting(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleting(e);
				if ((Volume_Error_TypeRowDeleting != null)) 
				{
					Volume_Error_TypeRowDeleting(this, new Volume_Error_TypeRowChangeEvent(((Volume_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			public void RemoveVolume_Error_TypeRow(Volume_Error_TypeRow row) 
			{
				Rows.Remove(row);
			}
		}
    
		[DebuggerStepThrough]
			public class Volume_Error_TypeRow : DataRow 
		{
        
			private Volume_Error_TypeDataTable tableVolume_Error_Type;
        
			internal Volume_Error_TypeRow(DataRowBuilder rb) : 
				base(rb) 
			{
				tableVolume_Error_Type = ((Volume_Error_TypeDataTable)(Table));
			}
        
			public int VolumeErrorTypeID 
			{
				get 
				{
					try 
					{
						return ((int)(this[tableVolume_Error_Type.VolumeErrorTypeIDColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableVolume_Error_Type.VolumeErrorTypeIDColumn] = value;
				}
			}
        
			public string ShortDesc 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableVolume_Error_Type.ShortDescColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableVolume_Error_Type.ShortDescColumn] = value;
				}
			}
        
			public string LongDesc 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableVolume_Error_Type.LongDescColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableVolume_Error_Type.LongDescColumn] = value;
				}
			}
        
			public bool UserSelectable 
			{
				get 
				{
					try 
					{
						return ((bool)(this[tableVolume_Error_Type.UserSelectableColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableVolume_Error_Type.UserSelectableColumn] = value;
				}
			}

			public string English 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableVolume_Error_Type.EnglishColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableVolume_Error_Type.EnglishColumn] = value;
				}
			}

			public string French 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableVolume_Error_Type.FrenchColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableVolume_Error_Type.FrenchColumn] = value;
				}
			}

			public string Spanish 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableVolume_Error_Type.SpanishColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableVolume_Error_Type.SpanishColumn] = value;
				}
			}
        
			public bool IsVolumeErrorTypeIDNull() 
			{
				return IsNull(tableVolume_Error_Type.VolumeErrorTypeIDColumn);
			}
        
			public void SetVolumeErrorTypeIDNull() 
			{
				this[tableVolume_Error_Type.VolumeErrorTypeIDColumn] = Convert.DBNull;
			}
        
			public bool IsShortDescNull() 
			{
				return IsNull(tableVolume_Error_Type.ShortDescColumn);
			}
        
			public void SetShortDescNull() 
			{
				this[tableVolume_Error_Type.ShortDescColumn] = Convert.DBNull;
			}
        
			public bool IsLongDescNull() 
			{
				return IsNull(tableVolume_Error_Type.LongDescColumn);
			}
        
			public void SetLongDescNull() 
			{
				this[tableVolume_Error_Type.LongDescColumn] = Convert.DBNull;
			}
        
			public bool IsUserSelectableNull() 
			{
				return IsNull(tableVolume_Error_Type.UserSelectableColumn);
			}
        
			public void SetUserSelectableNull() 
			{
				this[tableVolume_Error_Type.UserSelectableColumn] = Convert.DBNull;
			}
		}
    
		[DebuggerStepThrough]
			public class Volume_Error_TypeRowChangeEvent : EventArgs 
		{
        
			private Volume_Error_TypeRow eventRow;
        
			private DataRowAction eventAction;
        
			public Volume_Error_TypeRowChangeEvent(Volume_Error_TypeRow row, DataRowAction action) 
			{
				eventRow = row;
				eventAction = action;
			}
        
			public Volume_Error_TypeRow Row 
			{
				get 
				{
					return eventRow;
				}
			}
        
			public DataRowAction Action 
			{
				get 
				{
					return eventAction;
				}
			}
		}
    
		[DebuggerStepThrough]
			public class Division_TypeDataTable : DataTable, IEnumerable 
		{
        
			private DataColumn columnDivisionTypeID;
        
			private DataColumn columnTypeName;
        
			private DataColumn columnActiveType;
        
			private DataColumn columnNamedDivision;
        
			private DataColumn columnBaseTypeName;

			private DataColumn columnEnglish;

			private DataColumn columnFrench;

			private DataColumn columnSpanish;

        
			internal Division_TypeDataTable() : 
				base("Division_Type") 
			{
				InitClass();
			}
        
			internal Division_TypeDataTable(DataTable table) : 
				base(table.TableName) 
			{
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) 
				{
					CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) 
				{
					Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) 
				{
					Namespace = table.Namespace;
				}
				Prefix = table.Prefix;
				MinimumCapacity = table.MinimumCapacity;
				DisplayExpression = table.DisplayExpression;
			}
        
			[Browsable(false)]
			public int Count 
			{
				get 
				{
					return Rows.Count;
				}
			}
        
			internal DataColumn DivisionTypeIDColumn 
			{
				get 
				{
					return columnDivisionTypeID;
				}
			}
        
			internal DataColumn TypeNameColumn 
			{
				get 
				{
					return columnTypeName;
				}
			}
        
			internal DataColumn ActiveTypeColumn 
			{
				get 
				{
					return columnActiveType;
				}
			}
        
			internal DataColumn NamedDivisionColumn 
			{
				get 
				{
					return columnNamedDivision;
				}
			}
        
			internal DataColumn BaseTypeNameColumn 
			{
				get 
				{
					return columnBaseTypeName;
				}
			}

			internal DataColumn EnglishColumn 
			{
				get 
				{
					return columnEnglish;
				}
			}

			internal DataColumn FrenchColumn 
			{
				get 
				{
					return columnFrench;
				}
			}

			internal DataColumn SpanishColumn 
			{
				get 
				{
					return columnSpanish;
				}
			}
        
			public Division_TypeRow this[int index] 
			{
				get 
				{
					return ((Division_TypeRow)(Rows[index]));
				}
			}
        
			public event Division_TypeRowChangeEventHandler Division_TypeRowChanged;
        
			public event Division_TypeRowChangeEventHandler Division_TypeRowChanging;
        
			public event Division_TypeRowChangeEventHandler Division_TypeRowDeleted;
        
			public event Division_TypeRowChangeEventHandler Division_TypeRowDeleting;
        
			public void AddDivision_TypeRow(Division_TypeRow row) 
			{
				Rows.Add(row);
			}
        
			public Division_TypeRow AddDivision_TypeRow(int DivisionTypeID, string TypeName, bool ActiveType, bool NamedDivision, string BaseTypeName, string English, string Spanish, string French ) 
			{
				Division_TypeRow rowDivision_TypeRow = ((Division_TypeRow)(NewRow()));
				rowDivision_TypeRow.ItemArray = new object[] {
																 DivisionTypeID,
																 TypeName,
																 ActiveType,
																 NamedDivision,
																 BaseTypeName,
																 English,
																 French,
																 Spanish};
				Rows.Add(rowDivision_TypeRow);
				return rowDivision_TypeRow;
			}
        
			public IEnumerator GetEnumerator() 
			{
				return Rows.GetEnumerator();
			}
        
			public override DataTable Clone() 
			{
				Division_TypeDataTable cln = ((Division_TypeDataTable)(base.Clone()));
				cln.InitVars();
				return cln;
			}
        
			protected override DataTable CreateInstance() 
			{
				return new Division_TypeDataTable();
			}
        
			internal void InitVars() 
			{
				columnDivisionTypeID = Columns["DivisionTypeID"];
				columnTypeName = Columns["TypeName"];
				columnActiveType = Columns["ActiveType"];
				columnNamedDivision = Columns["NamedDivision"];
				columnBaseTypeName = Columns["BaseTypeName"];
				columnEnglish = Columns["English"];
				columnFrench = Columns["French"];
				columnSpanish = Columns["Spanish"];
			}
        
			private void InitClass() 
			{
				columnDivisionTypeID = new DataColumn("DivisionTypeID", typeof(int), null, MappingType.Element);
				Columns.Add(columnDivisionTypeID);
				columnTypeName = new DataColumn("TypeName", typeof(string), null, MappingType.Element);
				Columns.Add(columnTypeName);
				columnActiveType = new DataColumn("ActiveType", typeof(bool), null, MappingType.Element);
				Columns.Add(columnActiveType);
				columnNamedDivision = new DataColumn("NamedDivision", typeof(bool), null, MappingType.Element);
				Columns.Add(columnNamedDivision);
				columnBaseTypeName = new DataColumn("BaseTypeName", typeof(string), null, MappingType.Element);
				Columns.Add(columnBaseTypeName);
				columnEnglish = new DataColumn("English", typeof(string), null, MappingType.Element);
				Columns.Add(columnEnglish);
				columnFrench = new DataColumn("French", typeof(string), null, MappingType.Element);
				Columns.Add(columnFrench);
				columnSpanish = new DataColumn("Spanish", typeof(string), null, MappingType.Element);
				Columns.Add(columnSpanish);
			}
        
			public Division_TypeRow NewDivision_TypeRow() 
			{
				return ((Division_TypeRow)(NewRow()));
			}
        
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) 
			{
				return new Division_TypeRow(builder);
			}
        
			protected override Type GetRowType() 
			{
				return typeof(Division_TypeRow);
			}
        
			protected override void OnRowChanged(DataRowChangeEventArgs e) 
			{
				base.OnRowChanged(e);
				if ((Division_TypeRowChanged != null)) 
				{
					Division_TypeRowChanged(this, new Division_TypeRowChangeEvent(((Division_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowChanging(DataRowChangeEventArgs e) 
			{
				base.OnRowChanging(e);
				if ((Division_TypeRowChanging != null)) 
				{
					Division_TypeRowChanging(this, new Division_TypeRowChangeEvent(((Division_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowDeleted(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleted(e);
				if ((Division_TypeRowDeleted != null)) 
				{
					Division_TypeRowDeleted(this, new Division_TypeRowChangeEvent(((Division_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowDeleting(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleting(e);
				if ((Division_TypeRowDeleting != null)) 
				{
					Division_TypeRowDeleting(this, new Division_TypeRowChangeEvent(((Division_TypeRow)(e.Row)), e.Action));
				}
			}
        
			public void RemoveDivision_TypeRow(Division_TypeRow row) 
			{
				Rows.Remove(row);
			}
		}
    
		[DebuggerStepThrough]
			public class Division_TypeRow : DataRow 
		{
        
			private Division_TypeDataTable tableDivision_Type;
        
			internal Division_TypeRow(DataRowBuilder rb) : 
				base(rb) 
			{
				tableDivision_Type = ((Division_TypeDataTable)(Table));
			}
        
			public int DivisionTypeID 
			{
				get 
				{
					try 
					{
						return ((int)(this[tableDivision_Type.DivisionTypeIDColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.DivisionTypeIDColumn] = value;
				}
			}
        
			public string TypeName 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableDivision_Type.TypeNameColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.TypeNameColumn] = value;
				}
			}
        
			public bool ActiveType 
			{
				get 
				{
					try 
					{
						return ((bool)(this[tableDivision_Type.ActiveTypeColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.ActiveTypeColumn] = value;
				}
			}
        
			public bool NamedDivision 
			{
				get 
				{
					try 
					{
						return ((bool)(this[tableDivision_Type.NamedDivisionColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.NamedDivisionColumn] = value;
				}
			}
        
			public string BaseTypeName 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableDivision_Type.BaseTypeNameColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.BaseTypeNameColumn] = value;
				}
			}

			public string English 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableDivision_Type.EnglishColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.EnglishColumn] = value;
				}
			}

			public string French 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableDivision_Type.FrenchColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.FrenchColumn] = value;
				}
			}

			public string Spanish
			{
				get 
				{
					try 
					{
						return ((string)(this[tableDivision_Type.SpanishColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableDivision_Type.SpanishColumn] = value;
				}
			}
        
			public bool IsDivisionTypeIDNull() 
			{
				return IsNull(tableDivision_Type.DivisionTypeIDColumn);
			}
        
			public void SetDivisionTypeIDNull() 
			{
				this[tableDivision_Type.DivisionTypeIDColumn] = Convert.DBNull;
			}
        
			public bool IsTypeNameNull() 
			{
				return IsNull(tableDivision_Type.TypeNameColumn);
			}
        
			public void SetTypeNameNull() 
			{
				this[tableDivision_Type.TypeNameColumn] = Convert.DBNull;
			}
        
			public bool IsActiveTypeNull() 
			{
				return IsNull(tableDivision_Type.ActiveTypeColumn);
			}
        
			public void SetActiveTypeNull() 
			{
				this[tableDivision_Type.ActiveTypeColumn] = Convert.DBNull;
			}
        
			public bool IsNamedDivisionNull() 
			{
				return IsNull(tableDivision_Type.NamedDivisionColumn);
			}
        
			public void SetNamedDivisionNull() 
			{
				this[tableDivision_Type.NamedDivisionColumn] = Convert.DBNull;
			}
        
			public bool IsBaseTypeNameNull() 
			{
				return IsNull(tableDivision_Type.BaseTypeNameColumn);
			}
        
			public void SetBaseTypeNameNull() 
			{
				this[tableDivision_Type.BaseTypeNameColumn] = Convert.DBNull;
			}
		}
    
		[DebuggerStepThrough]
			public class Division_TypeRowChangeEvent : EventArgs 
		{
        
			private Division_TypeRow eventRow;
        
			private DataRowAction eventAction;
        
			public Division_TypeRowChangeEvent(Division_TypeRow row, DataRowAction action) 
			{
				eventRow = row;
				eventAction = action;
			}
        
			public Division_TypeRow Row 
			{
				get 
				{
					return eventRow;
				}
			}
        
			public DataRowAction Action 
			{
				get 
				{
					return eventAction;
				}
			}
		}
    
		[DebuggerStepThrough]
			public class File_Error_TypeDataTable : DataTable, IEnumerable 
		{
        
			private DataColumn columnFileErrorTypeID;
        
			private DataColumn columnShortDesc;
        
			private DataColumn columnLongDesc;
        
			internal File_Error_TypeDataTable() : 
				base("File_Error_Type") 
			{
				InitClass();
			}
        
			internal File_Error_TypeDataTable(DataTable table) : 
				base(table.TableName) 
			{
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) 
				{
					CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) 
				{
					Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) 
				{
					Namespace = table.Namespace;
				}
				Prefix = table.Prefix;
				MinimumCapacity = table.MinimumCapacity;
				DisplayExpression = table.DisplayExpression;
			}
        
			[Browsable(false)]
			public int Count 
			{
				get 
				{
					return Rows.Count;
				}
			}
        
			internal DataColumn FileErrorTypeIDColumn 
			{
				get 
				{
					return columnFileErrorTypeID;
				}
			}
        
			internal DataColumn ShortDescColumn 
			{
				get 
				{
					return columnShortDesc;
				}
			}
        
			internal DataColumn LongDescColumn 
			{
				get 
				{
					return columnLongDesc;
				}
			}
        
			public File_Error_TypeRow this[int index] 
			{
				get 
				{
					return ((File_Error_TypeRow)(Rows[index]));
				}
			}
        
			public event File_Error_TypeRowChangeEventHandler File_Error_TypeRowChanged;
        
			public event File_Error_TypeRowChangeEventHandler File_Error_TypeRowChanging;
        
			public event File_Error_TypeRowChangeEventHandler File_Error_TypeRowDeleted;
        
			public event File_Error_TypeRowChangeEventHandler File_Error_TypeRowDeleting;
        
			public void AddFile_Error_TypeRow(File_Error_TypeRow row) 
			{
				Rows.Add(row);
			}
        
			public File_Error_TypeRow AddFile_Error_TypeRow(int FileErrorTypeID, string ShortDesc, string LongDesc) 
			{
				File_Error_TypeRow rowFile_Error_TypeRow = ((File_Error_TypeRow)(NewRow()));
				rowFile_Error_TypeRow.ItemArray = new object[] {
																   FileErrorTypeID,
																   ShortDesc,
																   LongDesc};
				Rows.Add(rowFile_Error_TypeRow);
				return rowFile_Error_TypeRow;
			}
        
			public IEnumerator GetEnumerator() 
			{
				return Rows.GetEnumerator();
			}
        
			public override DataTable Clone() 
			{
				File_Error_TypeDataTable cln = ((File_Error_TypeDataTable)(base.Clone()));
				cln.InitVars();
				return cln;
			}
        
			protected override DataTable CreateInstance() 
			{
				return new File_Error_TypeDataTable();
			}
        
			internal void InitVars() 
			{
				columnFileErrorTypeID = Columns["FileErrorTypeID"];
				columnShortDesc = Columns["ShortDesc"];
				columnLongDesc = Columns["LongDesc"];
			}
        
			private void InitClass() 
			{
				columnFileErrorTypeID = new DataColumn("FileErrorTypeID", typeof(int), null, MappingType.Element);
				Columns.Add(columnFileErrorTypeID);
				columnShortDesc = new DataColumn("ShortDesc", typeof(string), null, MappingType.Element);
				Columns.Add(columnShortDesc);
				columnLongDesc = new DataColumn("LongDesc", typeof(string), null, MappingType.Element);
				Columns.Add(columnLongDesc);
			}
        
			public File_Error_TypeRow NewFile_Error_TypeRow() 
			{
				return ((File_Error_TypeRow)(NewRow()));
			}
        
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) 
			{
				return new File_Error_TypeRow(builder);
			}
        
			protected override Type GetRowType() 
			{
				return typeof(File_Error_TypeRow);
			}
        
			protected override void OnRowChanged(DataRowChangeEventArgs e) 
			{
				base.OnRowChanged(e);
				if ((File_Error_TypeRowChanged != null)) 
				{
					File_Error_TypeRowChanged(this, new File_Error_TypeRowChangeEvent(((File_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowChanging(DataRowChangeEventArgs e) 
			{
				base.OnRowChanging(e);
				if ((File_Error_TypeRowChanging != null)) 
				{
					File_Error_TypeRowChanging(this, new File_Error_TypeRowChangeEvent(((File_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowDeleted(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleted(e);
				if ((File_Error_TypeRowDeleted != null)) 
				{
					File_Error_TypeRowDeleted(this, new File_Error_TypeRowChangeEvent(((File_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			protected override void OnRowDeleting(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleting(e);
				if ((File_Error_TypeRowDeleting != null)) 
				{
					File_Error_TypeRowDeleting(this, new File_Error_TypeRowChangeEvent(((File_Error_TypeRow)(e.Row)), e.Action));
				}
			}
        
			public void RemoveFile_Error_TypeRow(File_Error_TypeRow row) 
			{
				Rows.Remove(row);
			}
		}
    
		[DebuggerStepThrough]
			public class File_Error_TypeRow : DataRow 
		{
        
			private File_Error_TypeDataTable tableFile_Error_Type;
        
			internal File_Error_TypeRow(DataRowBuilder rb) : 
				base(rb) 
			{
				tableFile_Error_Type = ((File_Error_TypeDataTable)(Table));
			}
        
			public int FileErrorTypeID 
			{
				get 
				{
					try 
					{
						return ((int)(this[tableFile_Error_Type.FileErrorTypeIDColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableFile_Error_Type.FileErrorTypeIDColumn] = value;
				}
			}
        
			public string ShortDesc 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableFile_Error_Type.ShortDescColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableFile_Error_Type.ShortDescColumn] = value;
				}
			}
        
			public string LongDesc 
			{
				get 
				{
					try 
					{
						return ((string)(this[tableFile_Error_Type.LongDescColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[tableFile_Error_Type.LongDescColumn] = value;
				}
			}
        
			public bool IsFileErrorTypeIDNull() 
			{
				return IsNull(tableFile_Error_Type.FileErrorTypeIDColumn);
			}
        
			public void SetFileErrorTypeIDNull() 
			{
				this[tableFile_Error_Type.FileErrorTypeIDColumn] = Convert.DBNull;
			}
        
			public bool IsShortDescNull() 
			{
				return IsNull(tableFile_Error_Type.ShortDescColumn);
			}
        
			public void SetShortDescNull() 
			{
				this[tableFile_Error_Type.ShortDescColumn] = Convert.DBNull;
			}
        
			public bool IsLongDescNull() 
			{
				return IsNull(tableFile_Error_Type.LongDescColumn);
			}
        
			public void SetLongDescNull() 
			{
				this[tableFile_Error_Type.LongDescColumn] = Convert.DBNull;
			}
		}
    
		[DebuggerStepThrough]
			public class File_Error_TypeRowChangeEvent : EventArgs 
		{
        
			private File_Error_TypeRow eventRow;
        
			private DataRowAction eventAction;
        
			public File_Error_TypeRowChangeEvent(File_Error_TypeRow row, DataRowAction action) 
			{
				eventRow = row;
				eventAction = action;
			}
        
			public File_Error_TypeRow Row 
			{
				get 
				{
					return eventRow;
				}
			}
        
			public DataRowAction Action 
			{
				get 
				{
					return eventAction;
				}
			}
		}
	}
}
